DROP DATABASE IF EXISTS tenant1;
DROP DATABASE IF EXISTS tenant2;
DROP DATABASE IF EXISTS tenant3;
DROP DATABASE IF EXISTS multi_tenant;

CREATE DATABASE IF NOT EXISTS tenant1;
CREATE DATABASE IF NOT EXISTS tenant2;
CREATE DATABASE IF NOT EXISTS tenant3;
CREATE DATABASE IF NOT EXISTS multi_tenant;